services:
  postgres:
    image: postgres:latest
    env_file:
      - ./config/env/development.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: template
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  data:
